title: λ Lambda Papers
email: sin@prajjwal.com
author: Prajjwal Singh
description: >
  On Programming, Linux, Computer Science, and Mathematics. Curated with λove by an impostor.
url: "https://lambdapapers.com"
twitter_username: prajjwalsin
github_username:  prajjwal
rss: rss

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
